development:
  clients:
    default:
      database: prices_dev
      hosts:
        - localhost:27017
      options:
        user: 'prices'
        password: 'netlabcom'
  options:
test:
  clients:
    default:
      database: prices_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: <%=ENV['mongodb_db']%>
      hosts:
        - 127.0.0.1:27017
      options:
        user: '<%=ENV['mongodb_user']%>'
        password: '<%=ENV['mongodb_pass']%>'
  options: