development:
  clients:
    default:
      database: prices_dev
      hosts:
        - localhost:27017
      options:
         user: 'prices'
         password: 'netlabcom'
  options:
test:
  clients:
    default:
      database: prices_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
